[build]
  command = "make build"
  functions = "functions"
  publish = "static"

[build.environment]
  GO_IMPORT_PATH = "github.com/mervin008/GOTTH"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200
